version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
    networks:
      - project.lpu
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - project.lpu

networks:
  project.lpu:
    driver: bridge
